### ISSUE TITLE
FileNotFoundException if .env doesn't exist

### ISSUE THREAD

**Issue by tomelkin** [LynxEyes/dotenv.clj#1]
Firstly, good work on the library!  Planning to use it in our project.

Just wanted to flag the fact that dotenv.clj throws an exception on load if it can't a .env file.  This breaks the way that we use dotenv (within our organisation anyway).  To explain-

.env is used for important credentials, so these don't get checked in to source control.
We tend to just put development environment credentials into .env.development (which your lib supports, which is great).
.env is deployed separately to all production servers.
This means we tend not to have a .env file on our dev machines.  This is where the FileNotFoundException causes us a problem.

If it could just treat .env as optional too, that would be great.

**Comment by ivopt** [comment]
OMG, you are totally right!

I've just pushed a new version that takes that into account.

Thank you so much for letting me know!

**Comment by tomelkin** [comment]
Awesome, thanks for the immediate turnaround!  

I can confirm it works as expected now.
